version: "3.2"

services:
  database:
    image: bitnami/cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./schema.cql:/docker-entrypoint-initdb.d/schema.cql
    environment:
      CASSANDRA_SEEDS: cassandra
      CASSANDRA_PASSWORD_SEEDER: "yes"
      CASSANDRA_PASSWORD: cassandra
